license="All rights reserved"

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# A URL to refer people to when problems occur with this mod
issueTrackerURL="http://my.issue.tracker/" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="hardercore" #mandatory

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory

# A display name for the mod
displayName="My First Mod" #mandatory

# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="http://myurl.me/" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="http://example.com/" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="examplemod.png" #optional

# A text field displayed in the mod UI
credits="It was made by Luke" #optional

# A text field displayed in the mod UI
authors="Luke" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
Making everything harder since 2021
'''

[[dependencies.hardercore]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.hardercore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,3]"
    ordering="NONE"
    side="BOTH"